### Importing Libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
weather_data = pd.read_csv('1. Weather Data.csv')

In [4]:
weather_data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [5]:
weather_data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [6]:
weather_data.tail()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

### Data Cleaning

In [8]:
# Renaming Weather Column to Weather Condition

weather_data.rename(columns={'Weather': 'Weather_Condition'}, inplace=True)

In [9]:
print(weather_data)

             Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4
1        1/1/2012 1:00    -1.8              -3.7         87                4
2        1/1/2012 2:00    -1.8              -3.4         89                7
3        1/1/2012 3:00    -1.5              -3.2         88                6
4        1/1/2012 4:00    -1.5              -3.3         88                7
...                ...     ...               ...        ...              ...
8779  12/31/2012 19:00     0.1              -2.7         81               30
8780  12/31/2012 20:00     0.2              -2.4         83               24
8781  12/31/2012 21:00    -0.5              -1.5         93               28
8782  12/31/2012 22:00    -0.2              -1.8         89               28
8783  12/31/2012 23:00     0.0              -2.1         86               30

      Visibility_km  Press_kPa     Weather_Condition
0               8.0     101.24                   Fog
1               8.0     101.24                   Fog
2               4.0     101.26  Freezing Drizzle,Fog
3               4.0     101.27  Freezing Drizzle,Fog
4               4.8     101.23                   Fog
...             ...        ...                   ...
8779            9.7     100.13                  Snow
8780            9.7     100.03                  Snow
8781            4.8      99.95                  Snow
8782            9.7      99.91                  Snow
8783           11.3      99.89                  Snow

[8784 rows x 8 columns]

In [11]:
# Checking Null Values

null_values = weather_data.isnull().sum()
print(null_values)

Date/Time            0
Temp_C               0
Dew Point Temp_C     0
Rel Hum_%            0
Wind Speed_km/h      0
Visibility_km        0
Press_kPa            0
Weather_Condition    0
dtype: int64

In [14]:
# Clear Weather_Conditions

clear_weather_records = weather_data[weather_data['Weather_Condition'] == 'clear']
print(clear_weather_records)

Empty DataFrame
Columns: [Date/Time, Temp_C, Dew Point Temp_C, Rel Hum_%, Wind Speed_km/h, Visibility_km, Press_kPa, Weather_Condition]
Index: []

In [15]:
# The number of times the wind speed was exactly 4 km/hr

wind_speed_4_count = (weather_data['Wind Speed_km/h'] == 4).sum()
print('Number of times wind speed was exactly 4 km/hr:', wind_speed_4_count)

Number of times wind speed was exactly 4 km/hr: 474

In [20]:
# Mean visibility of the dataset

mean_visibility = weather_data['Visibility_km'].mean()
print(mean_visibility)

27.664446721311478

In [21]:
# Number of records where wind speed is greater than 24 km/hr and visibility is equal to 25 km

wind_speed_visibility_count = weather_data[(weather_data['Wind Speed_km/h'] > 24) & (weather_data['Visibility_km'] == 25)].shape[0]
print(wind_speed_visibility_count)

308

In [25]:
# The mean value of each column for each weather condition

weather_data.describe()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

In [26]:
# Finding instances where weather is clear and relative humidity > 50 or visibility > 40
clear_humidity_visibility = weather_data[(weather_data['Weather_Condition'] == 'Clear') & ((weather_data['Rel Hum_%'] > 50) | (weather_data['Visibility_km'] > 40))]
print(clear_humidity_visibility)

             Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
114     1/5/2012 18:00    -7.1             -14.4         56               11
115     1/5/2012 19:00    -9.2             -15.4         61                7
116     1/5/2012 20:00    -9.8             -15.7         62                9
117     1/5/2012 21:00    -9.0             -14.8         63               13
241     1/11/2012 1:00   -10.7             -17.8         56               17
...                ...     ...               ...        ...              ...
8646   12/26/2012 6:00   -13.4             -14.8         89                4
8698  12/28/2012 10:00    -6.1              -8.6         82               19
8713   12/29/2012 1:00   -11.9             -13.6         87               11
8714   12/29/2012 2:00   -11.8             -13.1         90               13
8756  12/30/2012 20:00   -13.8             -16.5         80               24

      Visibility_km  Press_kPa Weather_Condition
114            25.0     100.71             Clear
115            25.0     100.80             Clear
116            25.0     100.83             Clear
117            25.0     100.83             Clear
241            25.0     101.49             Clear
...             ...        ...               ...
8646           25.0     102.47             Clear
8698           24.1     101.27             Clear
8713           25.0     101.31             Clear
8714           25.0     101.33             Clear
8756           25.0     101.52             Clear

[1220 rows x 8 columns]

In [27]:
# Counting the number of weather conditions that include snow

snow_conditions_count = weather_data[weather_data['Weather_Condition'].str.contains('Snow', na=False)].shape[0]
print('Number of weather conditions that include snow:', snow_conditions_count)

Number of weather conditions that include snow: 583